import type { Metadata } from "next";

import "./font/style.css"
import "./globals.css";
import { Header } from "@/components/global/Header"
import Footer from "@/components/global/Footer";
import { inter } from "@/app/font"
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Zanda CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className="scroll-smooth">

      <body className={`${inter.className}`}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>

    </html>
  );
}
